### ISSUE TITLE
3D prints 

### ISSUE THREAD

**Issue by LynnDelaere** [vives-project-xp/GoBabyGo2.1#11]
Er werden 3D prints getekend om de joystick te bevestigen ipv het stuur waarbij er gezorgd wordt dat de stuurstang niet zakt zodat de links rechts beweging nog kan uitgevoerd worden. De 3D prints zijn echter niet in het juiste formaat getekend.

**Comment by LynnDelaere** [comment]
3D prints werden aangepast en opnieuw ingegeven

**Comment by AlberiekDepreytere** [comment]
3D prints print structuur verwijderen + schuren voor vlotte doorgang van de kabels.
Moeren bevestigen in de Print. 

Scherpe hoeken vermijden en test monteren om een goeie werking te garanderen.

25/03 van 8:20 tot 10:10

**Comment by LynnDelaere** [comment]
3D prints werden geüpload in documentatie
