### ISSUE TITLE
Testen Joystick met auto

### ISSUE THREAD

**Issue by LynnDelaere** [vives-project-xp/GoBabyGo2.1#12]
Eens we een oplossing gevonden hebben voor de verbinding met de motordriver en de hardware aanwezig is voor deze verbinding. Kan de joystick getest worden met de auto

**Comment by AlberiekDepreytere** [comment]
Monteren van de Joystick in de auto + werking controleren.
Conclusie werkt naar behoren (Onderstuk 3D print nog eens herbevestigen.

(Overriden nog eens controleren.) Middag van 25/03 14:00 tot  20:00.

**Comment by AlberiekDepreytere** [comment]
Werkt naar behoren ook wanneer alles is aangesloten. getest en laatste volledige controle op 06/05.

**Comment by AlberiekDepreytere** [comment]
.
