### ISSUE TITLE
Ombouwkit

### ISSUE THREAD

**Issue by LynnDelaere** [vives-project-xp/GoBabyGo2.1#8]
File aangemaakt om documentatie bij te houden voor de ombouwkit

**Comment by bavolezy** [comment]
gaat da nie beter en gemakkelijker zijn als we handleiding parallel maken met de auto.
dus dawe een auto from scratch kunnen opvolgen foto's trekken en noteren wat te doen, dat zal dan ook preciezer zijn

**Comment by LynnDelaere** [comment]
ombouwkit wordt aangepast zodat er een Engelse en Nederlandse versie is voor het bevestigen van de joystick. Er wordt een handleiding gemaakt voor de ouders.

**Comment by LynnDelaere** [comment]
Document opgesteld en uitgetypt met uitleg hoe de ombouwkit moet gemaakt worden
